### ISSUE TITLE
Adding Bootstrap

### ISSUE THREAD

**Issue by semmasodo** [project-clara/project-clara#22]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
No CSS Framework is used

## Expected behavior
Include Bootstrap 4 

## What is the motivation / use case for changing the behavior?
Using Bootstrap in Clara

**Comment by toxitic** [comment]
Ich füge Now-UI hinzu... Pull Request folgt!

**Comment by semmasodo** [comment]
@toxitic  kann nach dem Merge zugemacht werden oder?

**Comment by TheDonDope** [comment]
#29 ist noch in der Pipeline der das Setup fixt, dann könnt hier zugemacht werden ;)
