### ISSUE TITLE
Meta: GitHub Account Namen

### ISSUE THREAD

**Issue by TheDonDope** [project-clara/project-clara#4]
Hi All,

bitte prüft mal eure GitHub Profil Infos und hinterlegt euren Namen (Abgekürzter Nachname ist auch in Ordnung), denn auch wenn Pseudonyme sehr cool sind, macht es das trotzdem schwerer zu wissen wer dahinter steckt 😉 

Danke 🎉

**Comment by toxitic** [comment]
Dürfte passiert sein! ;-)
